# --- !Ups
UPDATE ACL SET CG_NAME = '*' WHERE CG_NAME IS NULL;
ALTER TABLE ACL ALTER COLUMN CG_NAME SET NOT NULL;
ALTER TABLE ACL DROP CONSTRAINT acl_unique;
ALTER TABLE ACL ADD CONSTRAINT acl_unique UNIQUE (user_id, topic_id, role, cg_name);