# --- !Ups
CREATE TABLE TOPIC_SCHEMA_MAPPING (
  TOPIC_ID TEXT NOT NULL REFERENCES TOPIC(TOPIC_ID),
  SCHEMA TEXT NOT NULL,
  VERSION INT NOT NULL,
  CLUSTER TEXT NOT NULL,
  CREATED_TIMESTAMP TIMESTAMP DEFAULT now(),
  PRIMARY KEY (TOPIC_ID, SCHEMA, VERSION)
);