-- DDL generated by Postico 1.4.2
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE IF NOT EXISTS provision_user (
    userid text DEFAULT uuid_generate_v4() PRIMARY KEY,
    password text,
    username text UNIQUE,
    created_timestamp timestamp without time zone DEFAULT now(),
    claimed boolean,
    claimed_timestamp timestamp without time zone,
    cluster text
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX  IF NOT EXISTS username_uniqu ON provision_user(username text_ops);
CREATE UNIQUE INDEX  IF NOT EXISTS provision_user_pkey ON provision_user(userid text_ops);


-- DDL generated by Postico 1.4.2
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE  IF NOT EXISTS provision_topic (
    topicid text DEFAULT uuid_generate_v4() PRIMARY KEY,
    topic text UNIQUE,
    partitions integer,
    replicas integer,
    retentionms integer,
    cleanuppolicy text,
    created_timestamp timestamp without time zone DEFAULT now(),
    cluster text,
    organization text,
    updated_timestamp timestamp without time zone,
    description text
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX  IF NOT EXISTS topic_unique ON provision_topic(topic text_ops);
CREATE UNIQUE INDEX  IF NOT EXISTS provision_topic_pkey ON provision_topic(topicid text_ops);


-- DDL generated by Postico 1.4.2
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE  IF NOT EXISTS provision_consumergroup (
    consumergroupid text DEFAULT uuid_generate_v4(),
    userid text,
    topicid text,
    consumergroupname text,
    active boolean,
    created_timestamp timestamp without time zone DEFAULT now(),
    updated_timestamp timestamp without time zone,
    cluster text
);



-- DDL generated by Postico 1.4.2
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE  IF NOT EXISTS provision_acl (
    aclid text DEFAULT uuid_generate_v4() PRIMARY KEY,
    userid text,
    topicid text,
    role text,
    created_timestamp timestamp without time zone DEFAULT now(),
    cluster text,
    CONSTRAINT acl_unique UNIQUE (userid, topicid, role)
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX  IF NOT EXISTS provision_acl_pkey ON provision_acl(aclid text_ops);
CREATE UNIQUE INDEX  IF NOT EXISTS acl_unique ON provision_acl(userid text_ops,topicid text_ops,role text_ops);


-- DDL generated by Postico 1.4.2
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE OR REPLACE VIEW  credentials AS  SELECT provision_user.username,
    provision_user.password,
    provision_topic.topic,
    provision_acl.role,
    provision_consumergroup.consumergroupname,
    provision_user.cluster
   FROM provision_consumergroup,
    provision_acl,
    provision_user,
    provision_topic
  WHERE provision_consumergroup.topicid = provision_acl.topicid AND provision_acl.userid = provision_user.userid AND provision_acl.topicid = provision_topic.topicid AND provision_acl.role = 'consumer'::text AND provision_user.cluster = provision_topic.cluster AND provision_topic.cluster = provision_acl.cluster AND provision_acl.cluster = provision_consumergroup.cluster AND provision_consumergroup.active = true
UNION ALL
 SELECT provision_user.username,
    provision_user.password,
    provision_topic.topic,
    provision_acl.role,
    ''::text AS consumergroupname,
    provision_user.cluster
   FROM provision_acl,
    provision_user,
    provision_topic
  WHERE provision_acl.userid = provision_user.userid AND provision_acl.topicid = provision_topic.topicid AND provision_user.cluster = provision_topic.cluster AND provision_topic.cluster = provision_acl.cluster AND provision_acl.role = 'producer'::text;



-- DDL generated by Postico 1.4.2
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE OR REPLACE VIEW  consumergroups AS  SELECT provision_user.username,
    provision_topic.topic,
    provision_consumergroup.consumergroupname,
    provision_consumergroup.cluster
   FROM provision_consumergroup,
    provision_topic,
    provision_user
  WHERE provision_consumergroup.userid = provision_user.userid AND provision_consumergroup.topicid = provision_topic.topicid AND provision_consumergroup.active = true;



